.TH _PRINTF

.SH NAME
myprogram - a tool for processing data files


.TH myprogram 1 "November 2024" "1.0" "MyProgram Manual"
.SH NAME
myprogram - a brief description of your program
.SH SYNOPSIS
.B myprogram
.RI [ options ] " arguments"
.SH DESCRIPTION
This is a detailed description of your program. Include options, arguments, and examples.
.SH OPTIONS
.TP
.B -h, --help
Display help information.
.TP
.B -v, --version
Show version information.
.SH AUTHOR
Your Name <your.email@example.com>